### ISSUE TITLE
Unsupported 'format' value 'uuid'

### ISSUE THREAD

**Issue by slooker** [danielgtaylor/apisprout#38] opened 2019-04-15 19:01 UTC
When I have a string with a format of "uuid" I get the above error.

An example is as follows:

```
     requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sourceSystemId:
                  type: string
                  format: uuid
                  example: dd7d8481-81a3-407f-95f0-a2f1cb382a4b
```

**Comment by usumachi** [comment] 2019-04-23 15:40
Hi, @slooker !

Here, the difference between OpenAPI and Swagger about string formats.
OpenAPI: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types
Swagger: https://swagger.io/docs/specification/data-models/data-types/#string

The format 'uuid' is not supported by OAS(v3.0.2) but supported by Swagger.
So you cannot use this format with apisprout 😞

**Comment by yaronius** [comment] 2019-04-26 17:22
@usumachi actually, according to [OAS specification v3.0.2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#dataTypeFormat) `Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification.`. I suppose it means that such formats SHOULD NOT cause any errors.

**Comment by usumachi** [comment] 2019-04-27 14:26
@yaronius Oh, I see. You are right. Thank you for that.

@slooker I'm sorry for my wrong response.

**Comment by 0nse** [comment] 2019-05-29 13:14
@usumachi so how do we proceed? Removing `uuid` from our specs is not an option. I'd might offer a pull request but it seems as if this validation happens outside of this project. What needs to be changed?

**Comment by yaronius** [comment] 2019-05-29 13:35
I reproduced the issue, the complete error message is `Caught panic while trying to load: Validating Swagger failed: Unsupported 'format' value 'uuid'`. I traced this error to [this code](https://github.com/getkin/kin-openapi/blob/1e76a00e7163c16cb29b290778cec485b5ba7b7d/openapi3filter/router.go#L100) in a [third-party library](https://github.com/getkin/kin-openapi) for parsing OpenAPI. Thus, IMO, this issue has nothing to do with the current project and should be opened in the aforementioned library.

**Comment by yaronius** [comment] 2019-05-29 14:33
JFYI opened a PR to fix this issue in the kin-openapi library https://github.com/getkin/kin-openapi/pull/96

**Comment by larsks** [comment] 2019-05-30 20:56
Hah, I  was just stopping by to report the same problem. Unfortunately, the solution suggested in [the previous comment](https://github.com/danielgtaylor/apisprout/issues/38#issuecomment-496963112) isn't great, because it will still break for the next person who uses a custom value in `format`. Would it make sense to expose this as a command line parameter?  Something like:

    apisprout --add-string-format uuid --add-string-format isbn ...

**Comment by danielgtaylor** [comment] 2019-05-31 05:37
Looks like the discussion in getkin/kin-openapi#96 is leaning towards having us call `DefineStringFormat` for everything we support. I'm open to a PR that registers the formats supported in the [example generator](https://github.com/danielgtaylor/apisprout/blob/master/example.go#L38).

What are the use cases for custom format values? For example, do other tools support the `isbn` format or is it mainly for documentation?

**Comment by yaronius** [comment] 2019-05-31 13:59
My PR has just been merged, so we can proceed with fixing the issue. @danielgtaylor what do you think about @larsks idea to register custom formats as CLI params?

**Closed** 2023-11-06 19:31 UTC
Labels: bug, help wanted, upstream
